# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Build Android app, upload it to Firebase Distribution and invite testers automatically'
  lane :android_firebase_distribution do |_options|
    firebase_app_distribution(
      app: '1:381565657841:android:e6502d00cbd73f90997f50',
      firebase_cli_token: '1//09WrD_2heL6PYCgYIARAAGAkSNwF-L9IrNf6OPcptzAxCFPAZFfN4acYIP5M1MDfNiyhXIjPT0BKwyQhnXEtzXDEc7MepZCHoGi4',
      apk_path: '../build/app/outputs/apk/development/release/app-development-release.apk'
    )
  end
end
